### ISSUE TITLE
[GeoNature] Accueil - texte introduction

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#1]
Première version du texte d'accueil : 
Bienvenue sur _nom outil_
_Nom outil_ est la plateforme régionale du SINP  en Auvergne-Rhône-Alpes. Ce portail est dédié aux utilisateurs expérimentés (services de l’Etat, collectivités, associations, bureaux d’étude, etc.) et a pour objectif de permettre l’accès à l’information naturaliste géolocalisée.
Les données mises à disposition ont été collectées par le réseau des partenaires des Pôles thématiques d’Auvergne-Rhône-Alpes. Elles s’enrichissent de jour en jour mais ne peuvent être considérées comme exhaustives. 
Dans le cadre de l’Observatoire Régional de la Biodiversité, les Pôles thématiques sont là pour vous accompagner techniquement et scientifiquement, selon leurs domaines de compétences.
Pour en savoir plus sur l’ORB, les Pôles thématiques ou encore sur la mutualisation des données, rendez-vous sur le portail internet de l’Observatoire Régional de la Biodiversité (lien site web sur la fin de la phrase).
Par défaut, vous pouvez accéder à l’ensemble des données à la maille 5x5 km de la région Auvergne-Rhône-Alpes. Si vous souhaitez accéder aux données précisément localisées, vous devez accepter électroniquement une convention ponctuelle à l'aide du formulaire de demande de droits d'accès aux observations précises. 
La version actuelle de _nom outil_ correspond à une première version, elle fera l'objet d'une amélioration continue. Afin de vous orienter dans la prise en main des fonctionnalités de nom outil, nous vous invitons à consulter la Foire Aux Questions .

**Comment by jpm-cbna** [comment]
@okristo Nécessite de créer sur le CMS la page de la Foire aux question avec l'adresse : https://www.biodiversite-auvergne-rhone-alpes.fr/foire-aux-questions

**Comment by lvahe** [comment]
Il faut mettre à jour le texte de la page d'accueil de Biodiv'AURA Expert suite à la mise en conformité avec l'Open data.

Proposition de nouveau texte à intégrer : 

> Biodiv'AURA Expert est **la plateforme régionale du SINP en Auvergne-Rhône-Alpes**. Ce portail est dédié aux utilisateurs expérimentés (services de l’Etat, collectivités, associations, bureaux d’étude, etc.). En facilitant l’accès à l’information, **Biodiv’AURA Expert a pour objectif la connaissance et la conservation du patrimoine naturel régional**. C’est un outil public et collectif au service de la prise en compte de la biodiversité, financé et piloté de façon partenariale.
>
> Les données mises à disposition ont été collectées par le réseau des partenaires des Pôles thématiques d’Auvergne-Rhône-Alpes. Elles s’enrichissent de jour en jour mais **ne peuvent être considérées comme exhaustives** et nécessitent la consultation d’autres sources, une réactualisation et des inventaires complémentaires dans le cadre de l’expertise. 
>
> Les données de Biodiv’AURA Expert sont librement consultables à la précision maximale connue, **sauf pour les données sensibles**. En effet, [les données sensibles](https://www.biodiversite-auvergne-rhone-alpes.fr/documents/acces-aux-donnees-sensibles-du-sinp-auvergne-rhone-alpes) au titre de l’article L.124-4 du code de l’environnement tiennent lieu d’exception à la diffusion publique des données (publication en ligne et téléchargement). Il s’agit des données de localisation ne devant pas être largement diffusées pour éviter de porter atteinte aux éléments qu’elles concernent.
>
> Dans le cadre de l’Observatoire Régional de la Biodiversité, les Pôles thématiques sont là pour vous accompagner techniquement et scientifiquement, selon leurs domaines de compétences.
> 
> Pour en savoir plus sur l’ORB, les Pôles thématiques ou encore sur la mutualisation des données, rendez-vous sur[ le portail internet de l’Observatoire Régional de la Biodiversité ](https://www.biodiversite-auvergne-rhone-alpes.fr/).
> 
> La plateforme Biodiv'AURA Expert s'appuie sur les technologies GeoNature pour proposer un outil en amélioration continue. Afin de vous orienter dans la prise en main des fonctionnalités de Biodiv'AURA Expert, nous vous invitons à[ consulter la Foire Aux Questions ](https://www.biodiversite-auvergne-rhone-alpes.fr/foire-aux-questions).
