### ISSUE TITLE
[Atlas] Accueil - photo

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#11]
Remplacer photo
Choix en cours

**Comment by okristo** [comment]
Intégrer cette photo (en attendant d'avoir mieux !!!)
Je peux éventuellement recadrer pour virer le nom s'il s'affiche en trop gros (photo téléchargée sur Ajaris donc le nom s'affiche automatiquement)
![nielle_Ornella_Kristo](https://user-images.githubusercontent.com/61181043/119469715-e8250500-bd47-11eb-896e-be50c6f924b4.jpg)

**Comment by jpm-cbna** [comment]
C'est un Gazé (Aporia crataegi) et la fleur ?

**Comment by okristo** [comment]
Nielle des blés (Agrostemma githago)

**Comment by okristo** [comment]
Titre de la photo : Le Gazé sur la Nielle des blés

**Comment by jpm-cbna** [comment]
Ajout du nom de la plante sur la photo en ligne.
