### ISSUE TITLE
[Atlas] Texte page présentation

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#12]
Présentation de Nom Outil
A partir de 2021, l’Observatoire régional de la biodiversité d’Auvergne-Rhône-Alpes vous propose de consulter les données relatives à la faune, la flore et la fonge. S’appuyant sur trois pôles thématiques, Nom outil vous permet d’accéder à près de 12 millions de données sur l’ensemble du territoire régional.
Depuis 2011, le Pôle d’information flore-habitats-fonge (PIFH) d’Auvergne-Rhône-Alpes fédère un réseau de partenaires autour de la connaissance et de la préservation de la flore sauvage. Pas loin de 9 millions de données sont ainsi centralisées, standardisées et diffusées par les animateurs du Pôle (Conservatoire botanique national alpin et Conservatoire botanique national du Massif central).
En 2018, l’idée de créer un Pôle invertébrés d’Auvergne-Rhône-Alpes voit le jour ! L’organisation du réseau d’acteurs et son animation par l’association Flavia APE a déjà permis de centraliser plus de 1 million de données.
A partir de 2020, le Pôle thématique lié à la faune vertébrée vient compléter l’Observatoire de la biodiversité permettant ainsi d’ajouter 2 millions de données centralisées et standardisées d’une part par la LPO et d’autre part par la FRC.
Une des forces de l’Observatoire de la biodiversité d’Auvergne-Rhône-Alpes est sa volonté de diffuser une information de qualité. Une attention particulière est ainsi portée à la validation des données.
A travers Nom outil, chaque citoyen peut découvrir la biodiversité d’une commune et se familiariser avec la répartition des espèces sur l’ensemble du territoire régional.
Véritable carrefour biogéographique, le territoire d’Auvergne-Rhône-Alpes présente une variété de climats exceptionnel et présente une grande diversité d’espèces que nous vous invitons à découvrir dans Nom outil !

**Comment by jpm-cbna** [comment]
Est ce qu'on rajoute des liens vers les sites des différentes structures citées ?

**Comment by okristo** [comment]
Oui on peut rajouter les liens : 
http://www.flavia-ape.fr/
http://www.cbn-alpin.fr/
https://www.cbnmc.fr/
https://auvergne-rhone-alpes.lpo.fr/
http://www.chasseauvergnerhonealpes.com/

**Comment by okristo** [comment]
4è paragraphe : remplacer LPO par Ligue de protection des oiseaux (LPO) et FRC par Fédération régionale des chasseurs (FRC)

**Comment by okristo** [comment]
Mettre à jour le texte : 
Présentation de Biodiv'AURA Atlas
A partir de 2021, l’Observatoire régional de la biodiversité d’Auvergne-Rhône-Alpes vous propose de consulter les données relatives à la faune, la flore et la fonge. S’appuyant sur trois pôles thématiques, Biodiv'AURA Atlas vous permet d’accéder aux données de l’ensemble du territoire régional.

Depuis 2011, le Pôle d’information flore-habitats-fonge (PIFH) d’Auvergne-Rhône-Alpes fédère un réseau de partenaires autour de la connaissance et de la préservation de la flore sauvage. Plus de 10 millions de données sont ainsi centralisées, standardisées et diffusées par les animateurs du Pôle ([ Conservatoire botanique national alpin ](https://www.cbn-alpin.fr/)et [Conservatoire botanique national du Massif central ](https://www.cbnmc.fr/)).

En 2018, l’idée de créer un Pôle invertébrés d’Auvergne-Rhône-Alpes voit le jour ! L’organisation du réseau d’acteurs et son animation par l’association [Flavia APE](https://www.flavia-ape.fr/) a déjà permis de centraliser plus de 3 millions de données.

À partir de 2020, le Pôle thématique lié à la faune vertébrée vient compléter l’Observatoire de la biodiversité permettant ainsi d’ajouter 14 millions de données centralisées et standardisées d’une part par la [Ligue de protection des oiseaux (LPO) ](https://auvergne-rhone-alpes.lpo.fr/)et d’autre part par la [Fédération régionale des chasseurs (FRC) ](https://www.chasseauvergnerhonealpes.com/).


Une des forces de l’Observatoire de la biodiversité d’Auvergne-Rhône-Alpes est sa volonté de diffuser une information de qualité. Une attention particulière est ainsi portée à la validation des données.

À travers Biodiv'AURA Atlas, chaque citoyen peut découvrir la biodiversité d’une commune et se familiariser avec la répartition des espèces sur l’ensemble du territoire régional.

Véritable carrefour biogéographique, le territoire d’Auvergne-Rhône-Alpes présente une variété de climats exceptionnel et présente une grande diversité d’espèces que nous vous invitons à découvrir dans Biodiv'AURA Atlas !

**Comment by jpm-cbna** [comment]
Le texte est corrigé et en ligne : https://atlas.biodiversite-auvergne-rhone-alpes.fr/presentation
