### ISSUE TITLE
[Atlas] Mentions légales

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#14]
**[En cours de validation !!]**

### MENTIONS LÉGALES
Vous êtes sur le site officiel de Nom outil, plateforme régionale du Système d'information de l'INventaire du patrimoine naturel (SINP) de la région Auvergne-Rhône-Alpes. Ce site a pour objectif de permettre la visualisation des données d’occurrences pour les taxons de faune et de flore d’Auvergne-Rhône-Alpes.
Adresse : a définir

### Responsable de publication
Directeur de la publication, responsable légal : à définir

### Réalisation du site Internet
Le contenu éditorial et, sauf mention particulière, les productions photographiques, sont réalisés par l’équipe éditoriale constituée du Conservatoire Botanique National Alpin (CBNA), du Conservatoire Botanique National du Massif central (CBNMC), de FLAVIA APE, de la Ligue de protection des oiseaux (LPO), de la Fédération régionale des chasseurs (FRC), de la Région Auvergne-Rhône-Alpes et de la DREAL Auvergne-Rhône-Alpes.
La conception technique est effectuée par le Conservatoire Botanique National Alpin (CBNA).

### Serveurs et hébergements
Société OVH, RCS Roubaix-Tourcoing B 424 761 419
2, rue Kellerman, 59100 Roubaix

### Traitement et protection des données
Les données personnelles diffusées sur le site Nom outil via les données naturalistes (nom de l’observateur, date et lieu) résultent de la communication volontaire du fournisseur lors de l'envoi de ses données auprès de la plateforme Nom outil ou de l’un des Pôles thématiques.
Vous disposez d'un droit d'accès, de modification, de rectification et de suppression des données qui vous concernent (art. 34 de la loi "Informatique et Libertés").
Vous pouvez l'exercer par courriel en le précisant lors de votre demande : contact

### Établissements de liens
Lien depuis des sites tiers vers https://atlas.biodiversite-auvergne-rhone-alpes.fr/ : responsable publication autorise la mise en place d'un lien hypertexte depuis n'importe quel site Internet (sous réserve d'une information préalable), à l'exclusion de ceux diffusant des informations à caractère polémique, pornographique, xénophobe ou pouvant, dans une plus large mesure porter atteinte à la sensibilité du plus grand nombre. Le site doit apparaître dans une nouvelle fenêtre. Les pages du site ne doivent en aucun cas être intégrées à l'intérieur des pages d'un autre site (Frame ou iframe). Dans tous les cas, responsable publication se réserve le droit de demander la suppression d'un lien si il estime que le référent (site source) ne respecte pas les règles ainsi définies.
Lien depuis https://atlas.biodiversite-auvergne-rhone-alpes.fr/ vers des sites tiers : responsable publication et l’équipe éditoriale se réservent le droit de "pointer" vers des sites tiers. Accéder à ces liens ne vous fait pas quitter https://atlas.biodiversite-auvergne-rhone-alpes.fr/. Les sites cibles ne sont pas sous le contrôle de l’équipe éditoriale, par conséquent elle n'est pas responsable du contenu de ces sites, des liens qu'ils contiennent, ni des changements ou mises à jour qui leur sont apportés.

### Diffusion des données
La diffusion des données se fait conformément aux Chartes existantes des Pôles thématiques, documents de référence reconnus par les fournisseurs de données.
En utilisant le site, vous reconnaissez avoir pris connaissance de ces chartes et les avoir acceptées. Celles-ci pourront être modifiées à tout moment et sans préavis.
Nom outil présente l'ensemble des observations mises à dispositions par les adhérents du SINP et des fournisseurs synthétisées à la maille. Certaines données, qualifiées de sensibles ou privées peuvent ne pas être communiquées dans le respect des articles suivants du code de l’environnement :
L'article L311-5 du code des relations entre le public et l’administration précise les documents qui ne sont pas communicables :
Ne sont pas communicables les documents administratifs dont la consultation ou la communication porterait atteinte à (…) et aux cas définis à l'article L. 124-4 du code de l'environnement :
I.-Après avoir apprécié l'intérêt d'une communication, l'autorité publique peut rejeter la demande d'une information relative à l'environnement dont la consultation ou la communication porte atteinte :
(...)
2° A la protection de l'environnement auquel elle se rapporte ;
3° Aux intérêts de la personne physique ayant fourni, sans y être contrainte par une disposition législative ou réglementaire ou par un acte d'une autorité administrative ou juridictionnelle, l'information demandée sans consentir à sa divulgation ;
(...)
Article L124-4 du code de l'environnement
« I.-Le rejet d'une demande d'information relative à l'environnement est notifié au demandeur par une décision écrite motivée précisant les voies et délais de recours (...). »
Article L.124-6 du code de l’environnement

### Modalités de réutilisation des informations
L’utilisation des données se fait conformément aux chartes des Pôles thématiques, documents de référence reconnus par les fournisseurs de données. En utilisant le site, vous reconnaissez avoir pris connaissance des chartes et les avoir acceptées. Celles-ci pourront être modifiées à tout moment et sans préavis.
« Les informations publiques figurant dans des documents communiqués ou publiés par les administrations mentionnées au premier alinéa de l'article L. 300-2 peuvent être utilisées par toute personne qui le souhaite à d'autres fins que celles de la mission de service public pour les besoins de laquelle les documents ont été produits ou reçus.
Les limites et conditions de cette réutilisation sont régies par le présent titre. »
Article L321-1 du code des relations entre le public et l’administration
« Sauf accord de l'administration, la réutilisation des informations publiques est soumise à la condition que ces dernières ne soient pas altérées, que leur sens ne soit pas dénaturé et que leurs sources et la date de leur dernière mise à jour soient mentionnées. »
Article L322-1 du code des relations entre le public et l’administration
Consulter également les chartes des Pôles thématiques.

### Dispositions légales - Propriété
Le fait d'accéder au site ne donne pas le droit de l'utiliser sans l'accord de l’équipe éditoriale : tous les droits de reproduction sont réservés en vertu de l'article L.122-4 du code de la Propriété intellectuelle.
Toute utilisation des ressources (photographiques, iconographiques, textuelles ou relatives à la forme, la mise en page, la structure, les logotypes et les documents téléchargeables...) présentes sur ce site doit faire l'objet d'une autorisation expresse de l’équipe éditoriale.
À titre principal, l’équipe éditoriale concède une autorisation de visualisation du contenu du site.

### Responsabilité
La plate-forme Nom outil met tout en œuvre pour assurer une information fiable et une mise à jour fiable de ses sites internet. Toutefois, des erreurs ou omissions peuvent survenir. Nom outil ne peut garantir l’exhaustivité de l’information. responsable publication décline donc toute responsabilité en cas d'erreur ou d'omission.
L’utilisateur devra donc s'assurer de l'exactitude des informations et signaler toutes modifications du site qu'il jugerait utile.
Nom outil n'est en aucun cas responsable de l'utilisation faite de ces informations, et de tout préjudice direct ou indirect pouvant en découler.
L’équipe éditoriale se réserve le droit de modifier, tout ou partie des informations contenues dans les pages de ce site Internet, à tout moment et sans notification préalable.
Il appartient à l'utilisateur de ce site de prendre toutes les mesures appropriées de façon à protéger ses propres données et/ou logiciels de la contamination par d'éventuels virus circulant sur le réseau Internet. De manière générale, responsable publication décline toute responsabilité à un éventuel dommage survenu pendant la consultation du présent site.

**Comment by jpm-cbna** [comment]
Reste à remplacer : 
- [x] "Nom outil" qui est pour l'instant remplacé par "Biodiv'AURA Atlas"
- [ ] "Responsable publication" qui est pour l'instant remplacé par "le responsable de la publication"
- [ ] l'adresse du responsable de la publication
- [ ] le lien vers les chartes existantes des Pôles thématiques: à mettre en place dans le CMS ?

**Comment by okristo** [comment]
Version validée à mettre en ligne

MENTIONS LÉGALES
Vous êtes sur le site officiel de Biodiv’AURA, plateforme régionale du Système d'information de l'INventaire du patrimoine naturel (SINP) de la région Auvergne-Rhône-Alpes. Ce site a pour objectif de permettre la visualisation des données d’occurrences pour les taxons de faune et de flore d’Auvergne-Rhône-Alpes.
Institutions à l'initiative du site
Le présent site concerne l’ORB dont le comité de pilotage est co-présidé par l'Etat (DREAL, OFB) et la Région Auvergne-Rhône-Alpes.
Direction Régionale de l'Environnement de l'Aménagement et du Logement (DREAL) Auvergne-Rhône-Alpes
69453 Lyon Cedex 06
Tél. : 04 26 28 60 00  - <pn.ehn.dreal-ara@developpement-durable.gouv.fr>
Région Auvergne-Rhône-Alpes
1 esplanade François Mitterrand
CS 20033 - 69269 Lyon Cedex 02
Tél. 04 26 73 40 00 – DEE@auvergnerhonealpes.fr
Direction régionale de l’ Office français de la biodiversité
Parc de Parilly – Chemin des chasseurs – 69500 Bron
Tél : 04 72 78 89 41 - dr.auvergne-rhone-alpes@ofb.gouv.fr
Publication
La direction de la publication est assurée par le comité de pilotage de l'Observatoire, représenté par le directeur de la DREAL Auvergne-Rhône-Alpes, le directeur général des services de la Région Auvergne-Rhône-Alpes et le directeur régional de l’OFB.
L'enrichissement du site et la mise en ligne des contenus sont assurés par
•	Conservatoire botanique national alpin (CBNA) Domaine de Charance 05 000 GAP. Tél : 04 92 53 56 82 – cbna@cbn-alpin.fr
•	Conservatoire botanique national du Massif central (CBNMC) Le Bourg 43230 CHAVANIAC-LAFAYETTE. Tél : 04 71 77 55 65 - conservatoire.siege@cbnmc.fr
•	FLAVIA APE 10 route de Cozance 38460 TREPT. Tél : 06 08 32 84 50 – asso.flavia@gmail.com
•	Ligue de protection des oiseaux (LPO) Maison de l'Environnement, 14 avenue Tony Garnier 69007 Lyon. Tél : 04 37 61 05 06 - auvergne-rhone-alpes@lpo.fr
•	Fédération régionale des chasseurs (FRC) 10 Impasse Saint-Exupéry, BP 30152 Andrézieux-Bouthéon 42163 Cedex. Tél : 04 77 20 81 76 - contact@chasseauvergnerhonealpes.com

La conception technique est effectuée par le Conservatoire Botanique National Alpin (CBNA).
Serveurs et hébergements
Société OVH, RCS Roubaix-Tourcoing B 424 761 419
2, rue Kellerman, 59100 Roubaix
Traitement et protection des données
Les données personnelles diffusées sur le site Biodiv’AURA Atlas via les données naturalistes (nom de l’observateur, date et lieu) résultent de la communication volontaire du fournisseur lors de l'envoi de ses données auprès de la plateforme Biodiv’AURA ou de l’un des Pôles thématiques.
Vous disposez d'un droit d'accès, de modification, de rectification et de suppression des données qui vous concernent (art. 34 de la loi "Informatique et Libertés").
Vous pouvez l'exercer par courriel en le précisant lors de votre demande : o.kristo@cbn-alpin.fr
Établissements de liens
Lien depuis des sites tiers vers https://atlas.biodiversite-auvergne-rhone-alpes.fr/ : le comité de pilotage de l'Observatoire autorise la mise en place d'un lien hypertexte depuis n'importe quel site Internet (sous réserve d'une information préalable), à l'exclusion de ceux diffusant des informations à caractère polémique, pornographique, xénophobe ou pouvant, dans une plus large mesure porter atteinte à la sensibilité du plus grand nombre. Le site doit apparaître dans une nouvelle fenêtre. Les pages du site ne doivent en aucun cas être intégrées à l'intérieur des pages d'un autre site (Frame ou iframe). Dans tous les cas, le comité de pilotage de l'Observatoire se réserve le droit de demander la suppression d'un lien s’il estime que le référent (site source) ne respecte pas les règles ainsi définies.
Lien depuis https://atlas.biodiversite-auvergne-rhone-alpes.fr/ vers des sites tiers : le comité de pilotage de l'Observatoire et l’équipe éditoriale se réservent le droit de "pointer" vers des sites tiers. Accéder à ces liens ne vous fait pas quitter https://atlas.biodiversite-auvergne-rhone-alpes.fr/. Les sites cibles ne sont pas sous le contrôle de l’équipe éditoriale, par conséquent elle n'est pas responsable du contenu de ces sites, des liens qu'ils contiennent, ni des changements ou mises à jour qui leur sont apportés.
Diffusion des données
La diffusion des données se fait conformément aux Chartes existantes des Pôles thématiques, documents de référence reconnus par les fournisseurs de données.
En utilisant le site, vous reconnaissez avoir pris connaissance de ces chartes et les avoir acceptées. Celles-ci pourront être modifiées à tout moment et sans préavis.
Biodiv’AURA Atlas présente l'ensemble des observations mises à dispositions par les adhérents du SINP et des fournisseurs synthétisées à la maille de 5 x 5 km. 
Certaines données, qualifiées de sensibles ou privées peuvent ne pas être communiquées dans le respect des articles suivants du code de l’environnement :
L'article L311-5 du code des relations entre le public et l’administration précise les documents qui ne sont pas communicables :
Ne sont pas communicables les documents administratifs dont la consultation ou la communication porterait atteinte à (…) et aux cas définis à l'article L. 124-4 du code de l'environnement :
I.-Après avoir apprécié l'intérêt d'une communication, l'autorité publique peut rejeter la demande d'une information relative à l'environnement dont la consultation ou la communication porte atteinte :
(...)
2° A la protection de l'environnement auquel elle se rapporte ;
3° Aux intérêts de la personne physique ayant fourni, sans y être contrainte par une disposition législative ou réglementaire ou par un acte d'une autorité administrative ou juridictionnelle, l'information demandée sans consentir à sa divulgation ;
(...)
Article L124-4 du code de l'environnement
« I.-Le rejet d'une demande d'information relative à l'environnement est notifié au demandeur par une décision écrite motivée précisant les voies et délais de recours (...). »
Article L.124-6 du code de l’environnement
Modalités de réutilisation des informations
L’utilisation des données se fait conformément aux chartes des Pôles thématiques, documents de référence reconnus par les fournisseurs de données. En utilisant le site, vous reconnaissez avoir pris connaissance des chartes et les avoir acceptées. Celles-ci pourront être modifiées à tout moment et sans préavis.
« Les informations publiques figurant dans des documents communiqués ou publiés par les administrations mentionnées au premier alinéa de l'article L. 300-2 peuvent être utilisées par toute personne qui le souhaite à d'autres fins que celles de la mission de service public pour les besoins de laquelle les documents ont été produits ou reçus.
Les limites et conditions de cette réutilisation sont régies par le présent titre. »
Article L321-1 du code des relations entre le public et l’administration
« Sauf accord de l'administration, la réutilisation des informations publiques est soumise à la condition que ces dernières ne soient pas altérées, que leur sens ne soit pas dénaturé et que leurs sources et la date de leur dernière mise à jour soient mentionnées. »
Article L322-1 du code des relations entre le public et l’administration
Consulter également les chartes des Pôles thématiques.
Dispositions légales - Propriété
Le fait d'accéder au site ne donne pas le droit de l'utiliser sans l'accord de l’équipe éditoriale : tous les droits de reproduction sont réservés en vertu de l'article L.122-4 du code de la Propriété intellectuelle.
Toute utilisation des ressources (photographiques, iconographiques, textuelles ou relatives à la forme, la mise en page, la structure, les logotypes et les documents téléchargeables...) présentes sur ce site doit faire l'objet d'une autorisation expresse de l’équipe éditoriale.
À titre principal, l’équipe éditoriale concède une autorisation de visualisation du contenu du site.
Responsabilité
La plate-forme Biodiv’AURA Atlas met tout en œuvre pour assurer une information fiable et une mise à jour fiable de ses sites internet. Toutefois, des erreurs ou omissions peuvent survenir. Biodiv’AURA Atlas ne peut garantir l’exhaustivité de l’information. Le comité de pilotage de l'Observatoire décline donc toute responsabilité en cas d'erreur ou d'omission.
L’utilisateur devra donc s'assurer de l'exactitude des informations et signaler toutes modifications du site qu'il jugerait utile.
Le comité de pilotage de l'Observatoire n'est en aucun cas responsable de l'utilisation faite de ces informations, et de tout préjudice direct ou indirect pouvant en découler.
L’équipe éditoriale se réserve le droit de modifier, tout ou partie des informations contenues dans les pages de ce site Internet, à tout moment et sans notification préalable.
Il appartient à l'utilisateur de ce site de prendre toutes les mesures appropriées de façon à protéger ses propres données et/ou logiciels de la contamination par d'éventuels virus circulant sur le réseau Internet. De manière générale, le comité de pilotage de l'Observatoire décline toute responsabilité à un éventuel dommage survenu pendant la consultation du présent site.

**Comment by jpm-cbna** [comment]
@okristo Par rapport, a ton texte, j'ai l'email contact@biodiv... à la place du tien. Cela permet de pouvoir le change si nécessaire sans avoir à retoucher le site...

Pa ailleurs, il me semble que l'on devrait mieux distinguer la plateforme "**Biodiv’AURA"** du site "Biodiv’AURA **Atlas**". On parle plusieurs fois de **plateforme** "Biodiv’AURA **Atlas**" ...

Je n'ai pas de lien direct vers les pages des Chartes des Pôles. Du coup, j'ai mis l'adresse du CMS...
