### ISSUE TITLE
[GeoNature] : création de compte - pop up confirmation vide

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#16]
Lorsqu'on valide la création de compte, un rectangle rouge s'affiche en haut de la page mais il est vide
![image](https://user-images.githubusercontent.com/61181043/115146540-32cfa500-a057-11eb-85ee-6a01226b3606.png)

On ne sait pas si notre demande a été prise en compte ou non

**Comment by jpm-cbna** [comment]
Lié à la config SMTP.

**Comment by okristo** [comment]
Problème lorsqu'on souhaite créer un compte, au moment où on clique sur s'inscrire, un message d'erreur apparaît
![image](https://user-images.githubusercontent.com/61181043/119949344-126e0100-bf9a-11eb-95c5-cf33b792bce3.png)

**Comment by jpm-cbna** [comment]
C'est bon, c'est corrigé.
Je ne sais pas pourquoi mais il y a une manip qui change le propriétaire des fichiers de log des différents applis GeoNature vers _root_.  Cela change aussi la propriété des miniatures des media gérés dans TaxHub.
En repassant à _geonat_ la proriété de ces fichiers puis en relançant les services Supervisor, cela résout le problème.
