### ISSUE TITLE
[UsersHub] : erreur lors de la validation de compte

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#18]
Avec le compte admin, lorsque je clique sur la coche verte pour valider une demande de compte, l'erreur suivante apparaît 
![image](https://user-images.githubusercontent.com/61181043/115146673-c1442680-a057-11eb-8843-2fb6a31bb2e3.png)
Toutefois, la validation fonctionne bien malgré l'erreur

**Comment by jpm-cbna** [comment]
Problème lié à la config SMTP. C'est réglé.
