### ISSUE TITLE
[GeoNature] Accueil - pied de pages et logos

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#2]
Animateurs des pôles thématiques : 
Logos des 3 pôles thématiques + logos des animateurs (CBNA, CBNMC, FLAVIA, LPO, FRC) en suivant ce modèle :
![image](https://user-images.githubusercontent.com/61181043/114199323-7a1dad80-9954-11eb-86a0-4d5925902cf3.png)

Pilotes de l’Observatoire régional de la biodiversité :
Logos de la DREAL, Région et OFB
![Logo_Flavia_orange](https://user-images.githubusercontent.com/61181043/114199173-5ce8df00-9954-11eb-8cac-951c542f9a0d.png)
![logo_LPO-768x512](https://user-images.githubusercontent.com/61181043/114199177-5d817580-9954-11eb-834a-48a6990cd113.png)
![Logo_Po_le_flore-habitats-fonge-e1607781060686](https://user-images.githubusercontent.com/61181043/114199182-5e1a0c00-9954-11eb-864a-1537abf20320.png)
![Logo_Po_le_Inverte_bre_s-e1607781009791](https://user-images.githubusercontent.com/61181043/114199184-5e1a0c00-9954-11eb-8d6f-5076670ac107.png)
![Logo_Pole_vertebres-e1607781136184](https://user-images.githubusercontent.com/61181043/114199186-5eb2a280-9954-11eb-980a-f337963946df.png)
![Logo_region](https://user-images.githubusercontent.com/61181043/114199189-5eb2a280-9954-11eb-82bf-49a365b6cc22.png)
![logo-ofb-1](https://user-images.githubusercontent.com/61181043/114199190-5f4b3900-9954-11eb-8e92-23d1e4282681.png)
![frcaura-logo](https://user-images.githubusercontent.com/61181043/114199192-5f4b3900-9954-11eb-8e39-650e0fd96bdb.png)
![logo_cbnalpin-1](https://user-images.githubusercontent.com/61181043/114199195-5fe3cf80-9954-11eb-9cf3-3e0057665304.jpg)
![logo_cbnmassifcentral-1](https://user-images.githubusercontent.com/61181043/114199196-5fe3cf80-9954-11eb-9a2d-5edd72cd0641.jpg)
![logo_dreal-768x795](https://user-images.githubusercontent.com/61181043/114199198-607c6600-9954-11eb-8ca1-e3318dd06f04.png)

**Comment by jpm-cbna** [comment]
Logos des CBNs avec couleurs harmonisées:
![logo-cbna-couleurs-correctes](https://user-images.githubusercontent.com/51449363/115466299-2eaaaf80-a230-11eb-970c-a14860280f18.jpg)
![logo-cbnmc-couleurs-correctes](https://user-images.githubusercontent.com/51449363/115466310-310d0980-a230-11eb-9daa-b888149f0b67.jpg)

**Comment by okristo** [comment]
Logo Région à jour
![Logo-Region-Gris-pastille-Bleue-PNG-RVB (2)](https://user-images.githubusercontent.com/61181043/119462962-90839b00-bd41-11eb-8279-1ad616df92ac.png)

**Comment by jpm-cbna** [comment]
Finalement, il a été décidé d'uniformiser le pied de page avec celui du CMS https://www.biodiversite-auvergne-rhone-alpes.fr.

**Comment by okristo** [comment]
Selon la taille de l'écran, le logo ORB situé dans le pied de page est coupé dans le recherche par espèce et la recherche par commune.
Recherche par espèce : 
![image](https://user-images.githubusercontent.com/61181043/120925549-528b5d00-c6d9-11eb-822b-b7a2122608a0.png)
Recherche par commune : 
![image](https://user-images.githubusercontent.com/61181043/120925570-6c2ca480-c6d9-11eb-849b-53a3c8a96bbe.png)
D'ailleurs la carte affichée lors de la recherche par commune reste fixe et passe sous le pied de page

**Comment by jpm-cbna** [comment]
Le logo ORB n'est plus  tronqué et la carte ne se superpose plus au pied de page.
Au passage, j'ai aussi corrigé le problème du fond blanc du titre de la carte qui débordait sur la gauche.
