### ISSUE TITLE
[GeoNature] : données sous forme de polygônes

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#21]
Avec compte admin 
De nombreuses données apparaissent sous forme de polygônes (toutes les géométries en bleu ci-dessous)
![image](https://user-images.githubusercontent.com/61181043/115147076-90fd8780-a059-11eb-93fc-5a1e5d6acaa2.png)

Est-ce le comportement normal ?

**Comment by jpm-cbna** [comment]
C'est normal. C'est le rendu attendu puisqu'il a été décidé de prendre en compte les géométries de type surface lorsque justement la surface était petite : https://wiki-sinp.cbn-alpin.fr/database/sinp-aura/etat-avancement-import#notes_concernant_l_import_initial
