### ISSUE TITLE
[GeoNature] : message erreur accès au module synthèse

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#22]
Avec un compte utilisateur, sans avoir effectué de demande de compte, lorsqu'on entre dans le module synthèse, le message suivant s'affiche
![image](https://user-images.githubusercontent.com/61181043/115147151-f18cc480-a059-11eb-9c28-357eea2fb025.png)

**Comment by jpm-cbna** [comment]
Afin, d'éviter ce problème, il est nécessaire de [configurer les permissions comme indiquée dans la doc sur le wiki](https://wiki-sinp.cbn-alpin.fr/database/sinp-aura/import-donnees#configuration_des_permissions).
