### ISSUE TITLE
[Données] : données situées hors AURA

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#23]
Données situées hors AURA sont localisées au point même sans permission d'accès
Testé avec la recherche suivante : filtre date : date min = 01/01/2020

**Comment by jpm-cbna** [comment]
Je vais réaliser la même manip que pour le SINP PACA :
1. créer une table listant toutes les observations hors AURA.
2. Intégrer les mailles manquantes
2. Associer dans la table gn_synthese.cor_area_synthese les observations hors AURA aux nouvelles mailles ainsi qu'au territoire du SINP.

**Comment by okristo** [comment]
Pour les données situées hors AURA (environ 180) : suppression de la géométrie, export de ces données (donc non affichées et non interrogeables) et transmission aux CBN pour vérification pour la prochaine mise à jour
Données sans géométrie associée (environ 41 000) : données non affichées et non interrogeables. Export à envoyer aux CBN pour vérification pour la prochaine MAJ
