### ISSUE TITLE
[GeoNature] Afficher seulement les statuts s'appliquant en AURA

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#24]
Trier les statuts pour ne garder que ceux s'appliquant en AURA

**Comment by jpm-cbna** [comment]
Ce n'est pas si simple... Je te propose de reporter ça suite au travail qui sera effectué sur le sujet pour le SINP PACA.
Je réaliserai une doc sur le sujet permettant de faciliter cette restriction des statuts.

**Comment by okristo** [comment]
Oui, j'avais bien en tête que ce ne serait pas pour la v1 !

**Comment by jpm-cbna** [comment]
@okristo Peux tu confirmer que la demande de ce ticket est bien réalisé. Si oui, il faudrait le fermer.
