### ISSUE TITLE
[GeoNature] : problème demande d'accès

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#26]
Une erreur s'affiche lorsque l'utilisateur confirme la demande d'accès

![image](https://user-images.githubusercontent.com/61181043/115147639-3e719a80-a05c-11eb-9666-0e03685148ea.png)

Pourtant, la demande s'affiche bien dans le module admin et on peut la valider

**Comment by jpm-cbna** [comment]
À vérifier mais surement réglé avec la config SMTP.
