### ISSUE TITLE
[Atlas] : affichage logo observatoire

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#27]
Le logo de l'ORB en haut à gauche n'est pas visible
Prévoir de l'afficher sur fond blanc

**Comment by jpm-cbna** [comment]
Je viens de le passer sur fond blanc... mais je ne suis pas certain que cela améliore beaucoup le rendu. Le problème c'est les textes sur une si petite image. Je passe par Gimp pour redimensionner l'image et les texte sont vraiment dégradés...

Si tu sais comment améliorer le rendu de l'image, il faut une image de 60x60 pixels en PNG si possible avec des couleurs indexées pour diminuer la taille au max. Ou alors créer le PNG puis utiliser ce site pour diminuer la taille du fichier: https://tinypng.com/
