### ISSUE TITLE
[Atlas] : taxon au niveau genre dans la rubrique "à voir en ce moment"

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#28]
Prévoir de ne pas afficher les taxons de rang supérieur à l'espèce dans la rubrique "à voir en ce moment", peu d'intérêt et pas d'illustration proposée

**Comment by jpm-cbna** [comment]
J'ai regardé et il n'y a pas de paramètre pour gérer le rang.
Mais c'est bizarre comme comportement car si tu cliques sur le lien vers la fiche espèce, tu peux voir qu'elle possède bien des images...
Je n'ai pas vu de fichier en cache non plus qui expliquerai l’absence d'image.

Ce comportement est peut être lié aux données du CBNMC...

**Comment by jpm-cbna** [comment]
Ça à l'air corrigé maintenant que nous avons toutes les données. Il faut voir si cela se reproduit...
