### ISSUE TITLE
[Atlas] : logo ORB

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#31]
Modifier le logo ORB pour essayer de le rendre plus visible. Possible de tenter avec ce fichier ?
![Logo-observatoire_Auvergne-Rhone-Alpes - Copie](https://user-images.githubusercontent.com/61181043/117475526-6f0e6b00-af5c-11eb-9d4f-96fb02478d8d.jpg)

**Comment by jpm-cbna** [comment]
Ce n'est pas vraiment plus lisible.
Je vais ajouter le logo ORG dans le pied de page.
