### ISSUE TITLE
[GeoNature] : floutage des données sensibles

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#34]
La sensibilité n'a pas été bien renseignée dans les données préparées par CBNA et CBNMC.
Le champ code_nomenclature_sensitivity doit être renseigné pour que les données des espèces de la liste ci-dessous s'affichent de manière floutée (maille 5x5km) sauf si demande d'accès aux données précises sensibles.
[sp_sensibles.xlsx](https://github.com/cbn-alpin/sinp-aura-tickets/files/6570032/sp_sensibles.xlsx)

La version CSV :
[aura_taxons_sensibles.csv](https://github.com/cbn-alpin/sinp-aura-tickets/files/6570838/aura_taxons_sensibles.csv)

**Comment by jpm-cbna** [comment]
Ci-joints les fichiers des observations corrigées pour le CBNMC et le CBNA.
[fix_sensitivity_cbna.csv](https://github.com/cbn-alpin/sinp-aura-tickets/files/6570814/fix_sensitivity_cbna.csv)
[fix_sensitivity_cbnmc.csv](https://github.com/cbn-alpin/sinp-aura-tickets/files/6570815/fix_sensitivity_cbnmc.csv)
