### ISSUE TITLE
Fond de cartes (IGN, BRGM)

### ISSUE THREAD

**Issue by ch-cbnmc** [cbn-alpin/sinp-aura-tickets#36]
Demande de la possibilité d'affichage des fonds de cartes, pour les plus utilisés:
  - [x] IGN scan 25 (pas possible) => Utiliser Plan v2
  - [x] IGN orthophotos : soulève la question de la clé IGN, nous en avions une sur le PIFH mais les modalités ont changées depuis le début de l'année, je dois me renseigner => C'est bon.
  - [x] Cartes géologiques (1M, 50000è) (flux BRGM, gratuit) => À tester.

**Comment by jpm-cbna** [comment]
Pour le scan 25 après demande de Jean-Michel auprès d'IGN, ce n'est pas possible. Il faut utiliser le Plan v2.

Pour les orthophotos, c'est bon. Il n'y a plus de clé nécessaire.

Pour les cartes géologique, c'est gratuit mais le format utilisé est un peu particulier. Je n'ai pas encore réussi à intégrer ce fond carto dans un GeoNature.
