### ISSUE TITLE
Raccourci de Atlas ou Expert vers site ORB

### ISSUE THREAD

**Issue by ch-cbnmc** [cbn-alpin/sinp-aura-tickets#38]
Permettre un lien entre les pages de Biodiv'Expert et Biodiv'Atlas vers le CMS de l'ORB

**Comment by okristo** [comment]
Tu veux dire depuis le logo par exemple ?
Un lien est intégré depuis les textes d'accueil de l'atlas et d'Expert

**Comment by ch-cbnmc** [comment]
Oui exact, je cherchais un lien en étant déjà sur les outils, mais sur la page d'accueil finalement c'est bien suffisant.
