### ISSUE TITLE
Requête combinant espèce + commune

### ISSUE THREAD

**Issue by ch-cbnmc** [cbn-alpin/sinp-aura-tickets#39]
est-il possible de faire une requête sur une commune + une espèce (par exemple pour n'avoir que les plantes dans le résultat)?

**Comment by okristo** [comment]
Presque : il suffit de saisir l'objet de la recherche dans la barre située en haut à droite du tableau de résultats (dans le recherche par commune). L'exemple ci-dessous est une recherche sur une espèce mais on peut aussi rechercher sur les groupes (angiospermes,...) mais pas directement sur plantes ou plantae
![image](https://user-images.githubusercontent.com/61181043/124481129-4235d300-dda8-11eb-9490-beb6a4fe50fd.png)

**Comment by ch-cbnmc** [comment]
Effectivement, je n'aurai pas pensé à ça spontanément, mais c'est une façon d'y arriver! Merci
