### ISSUE TITLE
[Tout] Logo ORB

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#4]
Dans Atlas et dans Synthèse, logo ORB en haut à gauche
![Logo-observatoire_Auvergne-Rhone-Alpes](https://user-images.githubusercontent.com/61181043/114199459-9cafc680-9954-11eb-8e69-a9d7d4a4ea71.png)

**Comment by jpm-cbna** [comment]
Dans l'Atlas, ce n'est pas vraiment lisible.
Du coup, il sera rajouté dans le pied de page de l'Atlas et de GeoNature.
