### ISSUE TITLE
[GeoNature] Formulaire de demande d'accès

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#5]
_En italique, les modifs ou remarques par rapport à Silene_
Demande d'accès aux données précises
Accès _demandé_
Veuillez indiquer ci-dessous les zones géographiques pour lesquelles vous souhaitez accéder aux données à leur précision maximale. Merci de préciser également les groupes taxonomiques concernés et le calendrier de votre étude.
Accès jusqu'au
Zones géographiques 
Groupes taxonomiques
_Réactiver la case données sensibles_
Motivations de la demande
Veuillez décrire ci-dessous les motivations à l'origine de votre demande.
Règne concerné : _5 choix_ : Végétal, Animal (vertébrés et invertébrés), Animal (Vertébrés), Animal (Invertébrés), Animal et végétal
Veuillez indiquer le règne des taxons concernés par votre étude et pour lesquels vous demandez un accès précis.
Organisme
Veuillez indiquer le nom de l'organisme auquel vous appartenez.
Type d'étude ou de projet (laisser la liste présente dans SILENE pour l’instant)
Commanditaire
Veuillez indiquer le nom du commanditaire de l’étude ou l’organisme à l’origine du projet.
Description
_Précisez si vous êtes adhérents à l’un au moins des Pôles thématiques_
Précisez le calendrier, la finalité, l'objet de l’étude scientifique et le cadre réglementaire dans lequel s’inscrit la demande (Étude d'impact, étude d'incidence Natura 2000, étude d'incidence Eau, demande d'autorisation au titre de la loi sur l'eau, demande d'autorisation au titre des ICPE, demande d'autorisation de destruction d'espèces protégées).

**Comment by okristo** [comment]
Comme les données de faune vertébrée ne font pas l'objet de demande (accès à la précision maxi par défaut)
Modifier la ligne relative au règne concerné : 
Règne concerné : 3 choix : Végétal ; Animal (invertébrés), Végétal et Animal (invertébrés)
Veuillez indiquer le règne des taxons concernés par votre étude et pour lesquels vous demandez un accès précis. Pour rappel, les données de faune vertébrée sont accessibles à la précision maximale sans demande d'accès.

**Comment by okristo** [comment]
Ajouter "Auvergne-Rhône-Alpes" dans la liste des zones géographiques (pour demander un accès à toute la région)

**Comment by jpm-cbna** [comment]
> Règne concerné : 3 choix : Végétal ; Animal (invertébrés), Végétal et Animal (invertébrés)

Pour que cela soit perturbant pour l'utilisateur, je supprimerai  "(invertébrés)". Cela n'a plus de sens de laisser puisque l'on a supprimer l'option "(vertébrés)".
