### ISSUE TITLE
[GeoNature] : format exports

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#51]
Objectif du ticket : définir le format d'exports des données (fichier observations) de la synthèse

Les champs actuellement exportés:
EXPORT_COLUMNS = [ 
        "uuid_perm_sinp",
        "uuid_perm_grp_sinp",
        "ca_nom"
        "jdd_nom",
        "jdd_uuid",
        "niveau_validation",
        "validateur",
        "observateurs",
        "cd_ref",
        "nom_valide",
        "nombre_min",
        "nombre_max",
        "date_debut",
        "date_fin",
        "geojson_4326",
        "precision_geographique",
        "niveau_precision_diffusion",
    ]

Les champs disponibles pour l'export : 
 EXPORT_COLUMNS   = [
        "date_debut",
        "date_fin",
        "heure_debut",
        "heure_fin",
        "cd_nom",
        "cd_ref",
        "nom_valide",
        "nom_vernaculaire",
        "nom_cite",
        "regne",
        "group1_inpn",
        "group2_inpn",
        "classe",
        "ordre",
        "famille",
        "rang_taxo",
        "nombre_min",
        "nombre_max",
        "alti_min",
        "alti_max",
        "prof_min",
        "prof_max",
        "observateurs",
        "determinateur",
        "communes",
        "x_centroid_4326",
        "y_centroid_4326",
        "geometrie_wkt_4326",
        "nom_lieu",
        "comment_releve",
        "comment_occurrence",
        "validateur",
        "niveau_validation",
        "date_validation",
        "comment_validation",
        "preuve_numerique_url",
        "preuve_non_numerique",
        "jdd_nom",
        "jdd_uuid",
        "jdd_id",
        "ca_nom",
        "ca_uuid",
        "ca_id",
        "cd_habref",
        "cd_habitat",
        "nom_habitat",
        "precision_geographique",
        "nature_objet_geo",
        "type_regroupement",
        "methode_regroupement",
        "technique_observation",
        "biologique_statut",
        "etat_biologique",
        "biogeographique_statut",
        "naturalite",
        "preuve_existante",
        "niveau_precision_diffusion",
        "stade_vie",
        "sexe",
        "objet_denombrement",
        "type_denombrement",
        "niveau_sensibilite",
        "statut_observation",
        "floutage_dee",
        "statut_source",
        "type_info_geo",
        "methode_determination",
        "comportement",
        "reference_biblio",
        "id_synthese",
        "id_origine",
        "uuid_perm_sinp",
        "uuid_perm_grp_sinp",
        "date_creation",
        "date_modification",
        "champs_additionnels
    ]

**Comment by DonovanMaillard** [comment]
Bonjour, 

Le format actuel d'export pose question sur les invertébrés, justifiant certaines demandes spécifiques qui repassent par le Pôle Invertébrés. 

Plusieurs champs (Stade de vie, Sexe, Statut de l'observation (présence/absence) sont nécessaires pour une bonne réutilisation des données (a l'avenir il faudra pouvoir discerner les données de présence et d'absence). Dans l'idéal, nous aurions intérêt à diffuser les données les plus complètes et précises possibles, pour restituer au mieux les données des fournisseurs d'autant que pour les invertébrés, on incite fortement à nous transmettre les données les plus complètes possibles. 

Pour répondre aux contraintes de performances, peut-être qu'il faudra aussi se poser la question de fonctionner avec un autre mode de téléchargement , par exemple : 
- Sur des petits volumes, téléchargement en direct comme aujourd'hui
- Au delà d'un certain volume, on demande l'adresse mail de l'utilisateur et il reçoit un lien de téléchargement par mail (cf fonctionnement du module export)

Ca permettra aussi de logger les exports les plus volumineux et connaitre les adresses mails des principaux "consommateurs" de données pour les identifier et échanger.

**Comment by jpm-cbna** [comment]
> * Au delà d'un certain volume, on demande l'adresse mail de l'utilisateur et il reçoit un lien de téléchargement par mail (cf fonctionnement du module export)

Si cette option est retenue, cela nécessitera d'installer le module Export et de réaliser des tests afin d'évaluer aussi les limites de ce module. Mais tests en PACA avaient montré des limites à 150 000 données. Mais ils avaient été réalisés dans conditions non optimal.
Avec l'infrastructure mise en place en AURA, nous devrions pouvoir monter à 300 000 peut être 400 000 données par export. Cela reste à tester.

Par ailleurs, la mise en place de tels export nécessite, il me semble, la création de vues directement dans la base de GeoNature (à moins que le module est évoluée ?). Ainsi, cela demande un peu plus de temps et de compétences de la part des personnes en charge de l'administration des outils GeoNature. C'est donc à bien évaluer et à anticiper.

**Comment by DonovanMaillard** [comment]
non ma  proposition est simplement que même sur la synthèse, on passe par une tâche de fond avec envoi de mail en fin de process. Ca demanderait un développement si ce fonctionnement devait être retenu in fine

**Comment by jpm-cbna** [comment]
> non ma proposition est simplement que même sur la synthèse, on passe par une tâche de fond avec envoi de mail en fin de process

Ok, je comprends mieux. Oui, c'est effectivement une solution à retenir surtout si nous arrivons à faire sauter la limite des 50 000 données (développement demandé en PACA)...

**Comment by okristo** [comment]
Pour la MAJ d'avril 2022 et en attendant de définir plus précisément le format avec l'ensemble des animateurs de Pôles thématiques, reprendre la config actuelle de PACA en ajoutant l'information de présence/absence (champ statut_observation) : 
EXPORT_COLUMNS = [
        "uuid_perm_sinp",
        "uuid_perm_grp_sinp",
        "jdd_nom",
        "jdd_uuid",
        "fournisseur",
        "observateurs",
        "cd_ref",
        "nom_valide",
        "nom_vernaculaire",
        "classe",
        "famille",
        "ordre",
        "statut_observation",
        "nombre_min",
        "nombre_max",
        "date_debut",
        "date_fin",
        "geojson_4326",
        "x_centroid_4326",
        "y_centroid_4326",
        "precision_geographique",
        "communes",
        "alti_min",
        "technique_observation",
        "stade_vie",
        "statut_biologique",
        "sexe",
        "comportement",
        "type_source",
        "type_precision",
        "sensibilite",
        "confidentialite",
    ]

**Comment by jpm-cbna** [comment]
**Note** : l'ordre d'affichage des colonnes dans le fichier CSV dépend de l'ordre des colonnes dans la vue et non de l'ordre des champ dans le paramètre de config...

**Note** : nous utilisons ici une vue matérialisé pour accélérer les téléchargements (diminu par 2 le temps d'attente). Cela nécessite toutefois :
- d'avoir de l'espace disque en quantité suffisante.
- de penser à rafraîchir la vue matérialisée après chaque mise à jour des données de la synthèse.

Le script SQL de mise à jour de la vue:
```sql
BEGIN;

DROP VIEW IF EXISTS gn_synthese.v_synthese_for_export ;

DROP MATERIALIZED VIEW IF EXISTS gn_synthese.v_synthese_for_export ;

CREATE MATERIALIZED VIEW gn_synthese.v_synthese_for_export
AS
SELECT s.id_synthese,
	s.unique_id_sinp AS uuid_perm_sinp,
	s.unique_id_sinp_grp AS uuid_perm_grp_sinp,
	sd.dataset_name AS jdd_nom,
	sd.unique_dataset_id AS jdd_uuid,
	sd.organisms AS fournisseur,
	s.observers AS observateurs,
	t.cd_ref,
	t.nom_valide,
	t.nom_vern AS nom_vernaculaire,
	t.classe AS classe,
	t.famille AS famille,
	t.ordre AS ordre,
	n15.label_default AS statut_observation,
	s.count_min AS nombre_min,
	s.count_max AS nombre_max,
	s.date_min::date AS date_debut,
	s.date_max::date AS date_fin,
	st_asgeojson(s.the_geom_4326) AS geojson_4326, -- Use for SHP export and data blurring
	st_x(st_transform(st_centroid(s.the_geom_point), 4326)) AS x_centroid_4326,
	st_y(st_transform(st_centroid(s.the_geom_point), 4326)) AS y_centroid_4326,
	s."precision" AS precision_geographique,
	sa.communes,
	s.altitude_min AS alti_min,
	n3.label_default AS technique_observation,
	n10.label_default AS stade_vie,
	n5.label_default AS statut_biologique,
	n11.label_default AS sexe,
	n20.label_default AS comportement,
	n17.label_default AS type_source,
	s.additional_data ->> 'precisionLabel' AS type_precision,
	CASE
		WHEN ns.cd_nomenclature = '0' THEN 'donnée non sensible'
		WHEN s.id_nomenclature_sensitivity IS NULL THEN ''
		ELSE 'donnée sensible'
	END AS sensibilite,
	CASE
		WHEN s.additional_data ->> 'confidential' = 'true' THEN 'donnée confidentielle'
		ELSE 'donnée non confidentielle'
	END AS confidentialite,
	-- Fields use in internal
	sd.id_dataset AS jdd_id, -- Use for CRUVED
	s.id_digitiser AS id_digitiser, -- Use for CRUVED
	st_asgeojson(s.the_geom_local) AS geojson_local, -- Use for SHP export
	s.id_nomenclature_sensitivity, -- Use for data blurring
	s.id_nomenclature_diffusion_level -- Use for data blurring
FROM gn_synthese.synthese AS s
	JOIN taxonomie.taxref t ON t.cd_nom = s.cd_nom
	LEFT JOIN LATERAL (
		SELECT
			cas.id_synthese,
			string_agg(DISTINCT concat(a_1.area_name, ' (', a_1.area_code, ')'), ', '::text) AS communes
		FROM gn_synthese.cor_area_synthese AS cas
			JOIN ref_geo.l_areas AS a_1
				ON cas.id_area = a_1.id_area
			JOIN ref_geo.bib_areas_types AS ta
				ON ta.id_type = a_1.id_type AND ta.type_code::text = 'COM'::text
		WHERE cas.id_synthese = s.id_synthese
		GROUP BY cas.id_synthese
	) AS sa ON true
	LEFT JOIN LATERAL (
		SELECT
			td.id_dataset,
			td.dataset_name,
			td.unique_dataset_id,
			string_agg(DISTINCT bo.nom_organisme::text, ', '::text) AS organisms
		FROM gn_meta.t_datasets AS td
			 LEFT JOIN gn_meta.cor_dataset_actor cad
				ON (
					cad.id_dataset = td.id_dataset
					AND (
						cad.id_nomenclature_actor_role = ref_nomenclatures.get_id_nomenclature('ROLE_ACTEUR'::character varying, '5'::character varying)
						OR cad.id_nomenclature_actor_role = ref_nomenclatures.get_id_nomenclature('ROLE_ACTEUR'::character varying, '6'::character varying)
					)
				)
			 LEFT JOIN utilisateurs.bib_organismes bo
				ON bo.id_organisme = cad.id_organism
		WHERE td.id_dataset = s.id_dataset
		GROUP BY td.id_dataset
	) sd ON true
	LEFT JOIN ref_nomenclatures.t_nomenclatures AS n3 ON s.id_nomenclature_obs_technique = n3.id_nomenclature
	LEFT JOIN ref_nomenclatures.t_nomenclatures AS n5 ON s.id_nomenclature_bio_status = n5.id_nomenclature
	LEFT JOIN ref_nomenclatures.t_nomenclatures AS n10 ON s.id_nomenclature_life_stage = n10.id_nomenclature
	LEFT JOIN ref_nomenclatures.t_nomenclatures AS n11 ON s.id_nomenclature_sex = n11.id_nomenclature
            LEFT JOIN ref_nomenclatures.t_nomenclatures AS n15 ON s.id_nomenclature_observation_status = n15.id_nomenclature
	LEFT JOIN ref_nomenclatures.t_nomenclatures AS n17 ON s.id_nomenclature_source_status = n17.id_nomenclature
	LEFT JOIN ref_nomenclatures.t_nomenclatures AS n20 ON s.id_nomenclature_behaviour = n20.id_nomenclature
	LEFT JOIN ref_nomenclatures.t_nomenclatures AS ns ON s.id_nomenclature_sensitivity = ns.id_nomenclature
WITH DATA ;

CREATE UNIQUE INDEX idx_vsfe_id_synthese ON gn_synthese.v_synthese_for_export USING btree (id_synthese);
CREATE INDEX idx_vsfe_jdd_id ON gn_synthese.v_synthese_for_export USING btree (jdd_id);
CREATE INDEX idx_vsfe_id_digitiser ON gn_synthese.v_synthese_for_export USING btree (id_digitiser);
-- CREATE INDEX idx_vsfe_geojson_local ON gn_synthese.v_synthese_for_export USING btree (geojson_local);
CREATE INDEX idx_vsfe_id_nomenclature_sensitivity ON gn_synthese.v_synthese_for_export USING btree (id_nomenclature_sensitivity);
CREATE INDEX idx_vsfe_id_nomenclature_diffusion_level ON gn_synthese.v_synthese_for_export USING btree (id_nomenclature_diffusion_level);

COMMIT;
```

Le paramètre de config:
```properties
EXPORT_COLUMNS = [
        "uuid_perm_sinp",
        "uuid_perm_grp_sinp",
        "jdd_nom",
        "jdd_uuid",
        "fournisseur",
        "observateurs",
        "cd_ref",
        "nom_valide",
        "nom_vernaculaire",
        "classe",
        "famille",
        "ordre",
        "statut_observation",
        "nombre_min",
        "nombre_max",
        "date_debut",
        "date_fin",
        "geojson_4326",
        "x_centroid_4326",
        "y_centroid_4326",
        "precision_geographique",
        "communes",
        "alti_min",
        "technique_observation",
        "stade_vie",
        "statut_biologique",
        "sexe",
        "comportement",
        "type_source",
        "type_precision",
        "sensibilite",
        "confidentialite",
    ]
```

**Comment by DonovanMaillard** [comment]
Merci pour l'ajout des champs stade de vie et sexe notamment !

Avec l'automatisation des données (1ere mise en place ce jour entre Flavia et PINV, les 2 et 3eme sources automatisées arriveront dans les prochains jours), tu prévois un rafraichissement de la VM chaque jour ? Chaque semaine ? Sais-tu combien de temps son rafraichissement demande ?

**Comment by jpm-cbna** [comment]
@DonovanMaillard il faut que je fasse des tests complémentaires car je trouve des temps pratiquement similaire entre les exports en PACA et AURA. Or, en PACA, j'utilise la vue classique... 
Si l'on garde la VM, il est envisageable de faire des mises à jours toutes les nuits.

**Comment by DonovanMaillard** [comment]
Autre question : je vois que tu vas chercher precisionLabel dans les champs additionnels. J'utiliserai cette clé pour les centroides de mailles, communes ou départements des données provenant de l'INPN notamment. 

Outre cette clé en particulier, peut-on diffuser les champs additionnels ou est-ce que le format semble trop brut ? Je l'utilise personnellement lors des imports pour les données/champs qui ne répondent pas au standard (notamment quand on a une colonne nombre_males et une colonne nombre_femelles, par exemple).

**Comment by jpm-cbna** [comment]
Tests en production:

### Vue
 * Filtres : taxon "Quercus robur" => 18 427 obs
   * Affichage : 1,58s
   * Export obs csv : 16,58s
 * Filtres : rang taxonomique "Quercus" => 57 728 obs
   * Affichage : 6,11s
   * Export obs csv : 42,91s
 * Filtres : Département Ardèche => 87 996 obs
   * Affichage : 23,00s
   * Export obs csv : 45,06s
 * Filtres : date min 1er juin 2020 => max 100 000 obs
   * Affichage : 6,41s
   * Export obs csv : 51,65s

### Vue matérialisée
 * Filtres : taxon "Quercus robur" => 18 427 obs
   * Affichage : 2,12s
   * Export obs csv : 16,45s 
 * Filtres : rang taxonomique "Quercus" => 57 728 obs
   * Affichage : 6,91s
   * Export obs csv : 40,08s
 * Filtres : Département Ardèche => 87 996 obs
   * Affichage : 25,31s
   * Export obs csv : 51,30s
 * Filtres : date min 1er juin 2020 => max 100 000 obs
   * Affichage : 8,57s
   * Export obs csv : 59,02s

**Comment by DonovanMaillard** [comment]
surprenant ces scores... 

ça plaide donc de rester sur une vue, et de s'épargner un temps de rafraichissement ! 

Pour info coté invertébrés je suis en train de rentrer des données depuis OpenObs, j'ai automatisé Flavia, j'automatise arthropologia lundi et la LPO dans les prochains jours également. On va arriver à 2,5millions de données environ pour sans doute 7.000-8.000 taxons. Pas de quoi changer les stats, mais de quoi avoir un apport continu de données récentes :)

Sur l'instance PINV je mettrai en place les routes d'historisation nécessaires à GN2PG (coté fournisseur) et la vue nécessaire la semaine prochaine, tu pourras donc venir taper sur notre instance thématique pour fin avril en principe. 

Pour nos volumes, d'après mes tests des derniers jours, il faudra compter environ 12-15h de synchronisation je pense (mais 15mn de configuration de la source en termes de temps de main d'oeuvre une fois que gn2pg est installé)

**Comment by jpm-cbna** [comment]
> ça plaide donc de rester sur une vue, et de s'épargner un temps de rafraîchissement !

Oui, et effectivement. J'ai donc basculer sur la vue. Je ne comprends pas pourquoi la vue matérialisée n'est pas plus rapide... J'ai pourtant mis des index mais peut être pas aux bons endroits pour accélérer l'export. À creuser.

> il faudra compter environ 12-15h de synchronisation je pense (mais 15mn de configuration de la source en termes de temps de main d'oeuvre une fois que gn2pg est installé)

C'est noté. Je vais tester GN2PG la semaine prochaine en local. Puis je ferai l'installation en production et lancerai les mises à jours.
