### ISSUE TITLE
[Atlas] : erreur photo

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#54]
Un bug pour les photos d'Epipactis fibri : 
![image](https://user-images.githubusercontent.com/61181043/160149005-e0928dcd-312c-4935-b68a-87decc769b33.png)
cette image ne correspond pas à Epipactis fibri

Par contre lorsqu'on clique dessus, on a la bonne photo : 
![image](https://user-images.githubusercontent.com/61181043/160149152-8cba504d-0dee-4cfe-83cb-fb325d429c2a.png)

**Comment by jpm-cbna** [comment]
La mise à jour de l'Atlas a corrigé le problème. A voir dans le temps, si le problème survient à nouveau...
