### ISSUE TITLE
Bug téléchargement des observations sur Biodiv'Expert

### ISSUE THREAD

**Issue by qr-cbnmc** [cbn-alpin/sinp-aura-tickets#58]
Souci remonté par un de nos agents : il est impossible de télécharger les observations sur Biodiv'Expert suite à une requête, que ce soit en csv, geojson ou en shp. Un bandeau d'erreur s'affiche avec le message suivant : "500 - Internal Server Error undefined id requete: undefined".

Ce bug n'a pas lieu sur un compte admin et sur l'accès public.

Par contre, le téléchargement des taxons et des statuts fonctionne.

![Error_GeoNat](https://user-images.githubusercontent.com/100863670/171380250-1f864048-25f6-4973-ab33-de4fca7b1852.PNG)

**Comment by jpm-cbna** [comment]
Je viens de tester avec un compte standard et j'arrive à faire des exports.

@qr-cbnmc Il me faudrait plus d'information:
- nom ou identifiant de l'utilisateur ayant se problème (pour avoir une idée des permissions)
- valeurs des filtres utilisés pour réaliser la recherche dont l'export pose problème

**Comment by okristo** [comment]
J'ai le même problème avec mon compte okristo. Peu importe les filtres appliqués visiblement.
On a bcp de signalements de ce bug depuis 2 jours (y compris sur Silene).

**Comment by qr-cbnmc** [comment]
Je confirme, comme Ornella, que j'ai toujours ce problème et peu importe les filtres.

**Comment by jpm-cbna** [comment]
@okristo @qr-cbnmc Pouvez vous tester à nouveau ?
Nous avons corrigé un problème qui touchait uniquement les utilisateurs avec des permissions.
Je pense que mon utilisateur n'avait pas de permissions d'où l’absence de problème dans mon cas.

**Comment by jpm-cbna** [comment]
> On a bcp de signalements de ce bug depuis 2 jours (y compris sur Silene).

Oui, j'ai aussi corrigé le problème sur le SINP PACA. Au passage, nous avons activé le zonage à la maille 5km.

**Comment by qr-cbnmc** [comment]
C'est bon, il n'y a plus de problèmes lors du téléchargement. Cela fonctionne pour les différents formats.
