### ISSUE TITLE
[GeoNature] Mails demandes d'accès

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#6]
Dans le mail reçu par les administrateurs, remplacer **SILENE Expert** par _nom outil_
Mails d'acceptation, refus ou mise en attente : Remplacer dans Objet et dans texte du mail : **silene expert** par _nom outil_

**Comment by jpm-cbna** [comment]
En fait, cette information est issue du paramètre `appName` du fichier du config. Donc, le changement du paramètre dans le fichier de configuration modifie automatiquement le nom en question présent dans les emails.
