### ISSUE TITLE
[Atlas] Lenteur anormale de l'atlas

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#63]
Les temps d'obtention des résultats aux requêtes sur l'atlas semblent anormalement lents depuis peu.
En particulier : 
- Sur la page d'accueil, les statistiques de la rubrique "En quelques chiffres" n'apparaissent pas immédiatement comme c'était le cas auparavant ;
- sur la page d'accueil, les stats de la rubrique "espèces à découvrir" moulinent mais ne s'affichent pas
- lorsqu'on fait une requête sur une espèce, 30 à 40 s d'attente pour obtenir la fiche de l'espèce
- la recherche par commune ne présente pas ce type de souci a priori

**Comment by jpm-cbna** [comment]
Plusieurs dizaines de requêtes étaient toujours en cours d’exécution sur le serveur de base de données. Ce sont des requêtes effectuées depuis la Synthese en lien avec les statuts de protection qui n'aboutissaient pas.

J'ai forcé la suppression de ces requêtes depuis le serveur.

Le problème de performance est résolu.

Voir le ticket #61 pour un exemple de requête en erreur.
