### ISSUE TITLE
[Atlas] Observations visibles sur expert qui ne se retrouvent pas dans l'affichage par maille d'atlas

### ISSUE THREAD

**Issue by ch-cbnmc** [cbn-alpin/sinp-aura-tickets#64]
Après une remontée utilisateur = 
"Problème rencontré sur Biodiv’atlas : 2 observations précises de Colin (sur biodiv’expert) ne sont pas basculées sur Atlas (on ne retrouve pas les mailles). Il s’agit de 2 observations d’Orobanche hederae de 2015 avec les UUID suivants :
-	949ab134-9a05-4499-a5c5-5691d2f5099f
-	27ebd051-ddaa-4592-be41-c92ea126114b"

Ce sont des observations le long de l'Allier, en aval de Monistrol d'allier, pour situer en gros.

J’ai  cru voir 2 problèmes en cherchant un peu ; je n’approfondis pas plus dans le cas où je fasse fausse route, l’explication est pê ailleurs :

En partant de la requête  de la vue gn_synthese.v_area_taxon, j’ai vu que le schéma pour les objets géographiques est ref_geo_saved, et pas ref_geo. Et surtout que le contenu des tables de ces 2 schémas n’est pas exactement le même – notamment sur l’id_type de ref_geo.l_areas, ou ref_geo_saved.l_areas ou un même numéro ne correspond pas forcément au même attribut, en lien avec bib_areas_types.

Du coup je n’obtiens pas la même chose avec :

select * from gn_synthese.cor_area_synthese c
join ref_geo_saved.l_areas la2 on la2.id_area =c.id_area 
where c.id_synthese in (13583966, 15513339);

(la requête utilisée de ce que je comprends, et
là je n’ai plus que 15513339 dans le résultat)

Et 

select * from gn_synthese.cor_area_synthese c
join ref_geo.l_areas la on la.id_area =c.id_area
-- and la.id_type =37  -- pour mailles 5km
where c.id_synthese in (13583966, 15513339);

où là j’ai bien mes deux enregistrements.

Est-ce que le problème se situerait dans l'utilisation de ce schéma geo_ref_saved pour croiser l'information avec les mailles?

**Comment by jpm-cbna** [comment]
Alors je ne pense pas que la vue `gn_synthese.v_area_taxon` ait un rapport avec le problème. Ceci dit ce n'est pas normal qu'elle référence le schéma `ref_geo_saved`. Ce dernier contient les données du référentiel géographique de GeoNature d'origine. Nous avons en AURA utilisé le référentiel géographique fourni par Flavia.

Si le problème est bien au niveau de Biodiv’atlas, il te faut chercher dans la base `gnatlas`. Cette base contient des _foreign data tables_ (FDT) branchées sur la base `geonature2db`. Les vues matérialisés de `gnatlas` sont ensuite créées à partir des FDT.

**Comment by jpm-cbna** [comment]
A priori, les observations en question sont bien dans la vue `atlas.vm_observations` de l'Atlas.
Les id des obs:
- `949ab134-9a05-4499-a5c5-5691d2f5099f` a pour id `15513339`
- `27ebd051-ddaa-4592-be41-c92ea126114b` a pour id `13583966`

**Comment by jpm-cbna** [comment]
@ch-cbnmc Est ce que le problème n'est pas le même que celui du [ticket suivant remonté sur le SINP PACA](https://github.com/cbn-alpin/sinp-paca-tickets/issues/210) ?

**Comment by jpm-cbna** [comment]
Au 15 mars 2023 ce problème est résolu. Voi PJ ci-jointe. Les 2 observations en question apparaissent bien sur l'Atlas. C'est bien lié au ticket cbn-alpin/sinp-paca-tickets#210.
Le problème a été résolu en utilisant pour le filtre des observations de l'Atlas (vue `sysntheseff`) les mêmes critères que pour le floutage dans [GeoNature Expert](https://donnees.biodiversite-auvergne-rhone-alpes.fr/).
![Screenshot_20230315_111747](https://user-images.githubusercontent.com/51449363/225280474-8b33c046-81be-42ee-88de-38065124190d.png)
