### ISSUE TITLE
[GeoNature] Création de compte - texte

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#7]
Texte en fin de formulaire
«  j’accepte les conditions d’utilisation et les chartes des Pôles thématiques »
Merci pour votre demande d’inscription. Après validation par l’administrateur, vous pourrez accéder à l'ensemble des données à l'échelle de la maille 5x5km.
L'accès aux données avec leur précision maximale nécessite, dans nom outil, de compléter un « formulaire de demande d’accès aux données précises ». L'accord sera formalisé par l’acceptation d' une convention « droit d'accès aux données précises » et donnera lieu à l'attribution d'un accès direct à ces données. La convention engage le titulaire à un bon usage des données et à une alimentation de nom outil en retour.
Les autorisations d'accès sont gérées par les animateurs des Pôles thématiques s'appuyant sur le Comité de pilotage de l’ORB (ou de nom SINP AURA).
Les données et informations qui vous sont fournies dans le cadre de nom outil ne sont pas exhaustives et peuvent donc s’avérer insuffisantes pour les besoins spécifiques de votre étude. Une réactualisation de ces données dans le cadre d’inventaires complémentaires est nécessaire.

**Comment by jpm-cbna** [comment]
Je suppose que la phrase _« j’accepte les conditions d’utilisation et les chartes des Pôles thématiques »_ correspond au texte de la case à cocher ?
