### ISSUE TITLE
[GeoNature] Personnaliser la page de connexion de Biodiv'AURA Expert

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#71]
Sur la page d'accueil (avant connexion) : insérer les logos de l'ORB et des 3 Pôles thématiques et modifier la photo.
Proposition de photo à venir.

**Comment by okristo** [comment]
Voici la photo à utiliser pour la page d'accueil (avant connexion ou clic sur "accès public")

![Lapin-de-garenne-©-Géraldine-Le-Duc-LPO-scaled-e1607721707244 (2)](https://github.com/cbn-alpin/sinp-aura-tickets/assets/61181043/9feccf72-6ca7-44ac-aae6-2c9b69dfece0)

**Comment by jpm-cbna** [comment]
Il faudrait m'indiquer:
- où placer les logos sur l'image.
- le titre à mettre pour la photo
- l'auteur de la photo (nom et prénom)
- la licence de la photo

Je vais déjà tester ce que cela donne avec la taille de la photo fournie.

**Comment by okristo** [comment]
Logos : en bas à droite de l'image (attention, selon taille de l'écran, la visibilité des logos peut varier)
Titre photo : Lapin de garenne
Auteur : Géraldine Le Duc
Licence : je me renseigne

**Comment by jpm-cbna** [comment]
Voilà, je viens de mettre en ligne une première version. J'ai mis un © en attendant le retour sur la licence. Il faudrait aussi savoir s'il faut préciser un nom d'organisme après le nom de l'auteur (si la photo a été prise dans le cadre du travail).

Dit moi ce que tu en penses ?

Tout est géré via les CSS car je n'ai pas la possibilité de modifier le HTML de la page de login. J'ai testé sur Chrome et Firefox et cela fonctionne bien.

Si l'image ne s'actualise pas toute seule, il faut forcer l'actualisation avec `CTRL+MAJ+R`.

**Comment by okristo** [comment]
Merci
Après la photo, préciser le nom de l'organisme : LPO
Les logos ne sont pas bien visibles. On peut les remplacer par ceux-ci (avec fond blanc).

![logo_PIFH_fond_blanc](https://github.com/cbn-alpin/sinp-aura-tickets/assets/61181043/8fb33bb6-92f2-4b74-bc68-1197c8997f46)
![Logo-observatoire_AuRA_fond_blanc (2)](https://github.com/cbn-alpin/sinp-aura-tickets/assets/61181043/b4305353-05f9-472e-ac36-e026a3aa53af)
![logo_PF_fond_blanc](https://github.com/cbn-alpin/sinp-aura-tickets/assets/61181043/9396d66b-426f-4df3-b666-b8dcfa3aa023)
![logo_PI_fond_blanc](https://github.com/cbn-alpin/sinp-aura-tickets/assets/61181043/2c186370-a34b-4dea-9d2c-219ce67d593d)

**Comment by jpm-cbna** [comment]
@okristo je te propose plutôt d'insérer le fond blanc via les CSS. Je peux facilement rajouter une cadre blanc sous les logos. Je vais le faire en ligne pour avoir ton retour.
Voici la version avec un cadre blanc:
![Screenshot_20230808_152517](https://github.com/cbn-alpin/sinp-aura-tickets/assets/51449363/150f4f45-c6a9-418b-ab46-30513948ef14)

S'il faut absolument que le fond blanc soit rond uniquement sous les logos c'est aussi possible:
![Screenshot_20230808_152638](https://github.com/cbn-alpin/sinp-aura-tickets/assets/51449363/6121a44b-cedd-49f2-8718-bfaa4b5f99b6)

Je suppose que tu préféreras la seconde version, je mets donc celle là en ligne pour l'instant.
