### ISSUE TITLE
[GeoNature] Modifier le formulaire de demande d'accès

### ISSUE THREAD

**Issue by jpm-cbna** [cbn-alpin/sinp-aura-tickets#72]
Prochainement, il va devenir nécessaire de modifier le formulaire de demande d'accès pour y supprimer la notion d'accès aux données "privées".

Pour ce faire, nous pourrons:
 - [x] <del>ajouter 2 paramètres (spécifique à la branche SINP) permettant de modifier le titre du formulaire et le texte de la case à cocher "sensibilité". Par défaut, ces 2 paramètres contiendront les textes actuels.</del> Mise en place de la possibilité de surcharger les textes des traductions présentes dans `frontend/src/assets/i18n/` en utilisant un fichier `<lang>.override.json` contenant seulement les texte à remplacer.
 - [x] le titre du formulaire pour Biodiv'Aura deviendra "`Demande d'accès aux données sensibles précises`"
 - [x] le texte de la case à cocher deviendra "`Je confirme avoir pris connaissance des modalités d'accès aux données sensibles précises`" avec un lien vers les modalités d'accès (sur page de l'ORB).
 
Nous pourrons aussi pour le formulaire "Motivation de la demande" :
 - [x] Sous le champ "Règne concerné" : supprimer le texte "Pour rappel, les données de faune vertébrée sont accessibles à la précision maximale sans demande d'accès."
 - [x] Sous le champ "Règne concerné" mettre : "`Veuillez indiquer le règne des taxons concernés par votre étude et pour lesquels vous demandez un accès précis aux données sensibles.`"
 - [x] Sous le champ "Description" : supprimer la balise "`<br/>`" qui s'affiche dans le texte final.
 - [x] Sous le champ "Description" : "`Précisez le calendrier, la finalité, l'objet de l'étude scientifique et le cadre réglementaire dans lequel s'inscrit la demande (Étude d'impact, étude d'incidence Natura 2000, étude d'incidence Eau, demande d'autorisation au titre de la loi sur l'eau, demande d'autorisation au titre des ICPE, demande d'autorisation de destruction d'espèces protégées).`"

Modifier le texte de la convention (voir avec @okristo).

Nous ne modifierons pas le comportement du formulaire qui ajoute des droits d'accès aux données privés car le code ne sera de toute façon pas maintenu à terme...

**Comment by okristo** [comment]
Le titre du formulaire deviendra "Demande d'accès aux données sensibles précises".
Le texte de la case à cocher deviendra : "Je confirme avoir pris connaissance des modalités d'accès aux données sensibles précises" avec un lien vers les modalités d'accès (sur page de l'ORB, lien à ajouter).

Sous le champ "Règne concerné" : Veuillez indiquer le règne des taxons concernés par votre étude et pour lesquels vous demandez un accès précis aux données sensibles.
Sous le champ "Description" : Précisez le calendrier, la finalité, l'objet de l'étude scientifique et le cadre réglementaire dans lequel s'inscrit la demande (Étude d'impact, étude d'incidence Natura 2000, étude d'incidence Eau, demande d'autorisation au titre de la loi sur l'eau, demande d'autorisation au titre des ICPE, demande d'autorisation de destruction d'espèces protégées).

Il faudra mettre à jour la convention qui s'affiche lorsqu'on clique sur "Envoyer" (je proposerai un texte)

**Comment by jpm-cbna** [comment]
Fait dans les commits : https://github.com/PnX-SI/GeoNature/commit/42483418afac4792f2b533cd5c2cdeaab26cfd40 et https://github.com/PnX-SI/GeoNature/commit/36478b98233926ffa8de201d416a434861c8cfe6

**Comment by okristo** [comment]
- [x] Texte de la convention pour mise à jour : 
[Convention_DS_2024.docx](https://github.com/cbn-alpin/sinp-aura-tickets/files/15496931/Convention_DS_2024.docx)
 - [x] Rendre la coche "Je confirme avoir pris connaissance des modalités d'accès aux données sensibles précises" obligatoire et remplacer le lien actuel par celui-ci : https://www.biodiversite-auvergne-rhone-alpes.fr/documents/acces-aux-donnees-sensibles-du-sinp-auvergne-rhone-alpes/#
 - [x] Supprimer " Pour rappel, les données de faune vertébrée sont accessibles à la précision maximale sans demande d'accès." dans la rubrique règne concerné ; 
 - [x] Supprimer " Précisez si vous êtes adhérents à l'un au moins des Pôles thématiques." dans la rubrique description
