### ISSUE TITLE
Problème validation compte utilisateur

### ISSUE THREAD

**Issue by qr-cbnmc** [cbn-alpin/sinp-aura-tickets#73]
Le 27/03/2023 à 14:23, une demande de création de compte est faite par un salarié du BE Acer campestre (a.bo...@acer-campestre.fr). Étonnamment, cette personne a fait une demande d'accès à des données à 14:30, avant que je ne puisse valider la création de son compte dans le UserHub. La demande de création de compte est toujours visible dans le UserHub et impossible à mon niveau de valider le compte. Si j'essaie, le message suivant apparait : "Erreur durant la validation de l'utilisateur temporaire"
![317471481-f3288687-caa3-4a9e-b040-1f934ed50ee2](https://github.com/cbn-alpin/sinp-aura-tickets/assets/51449363/406109ac-d34c-48f4-8195-48bd1bb042da)

**Comment by jpm-cbna** [comment]
L'utilisateur en question a déjà un compte qui porte l'id 2592898. Je pense qu'il a voulu créé un nouveau compte avant de s'apercevoir qu'il en avait déjà un...

Tu n'arrives pas à valider la demande de compte car il a utilisé un email qui existe déjà dans la base sur le compte 2592898. J'ai du rajouté un index unique sur le champ email dans la base de données pour éviter de nombreux problème.

Je pensai que lors de la demande compte il y avait une vérification de la présence de l'email dans la base mais apparemment ce n'est pas le cas. C'est juste fait pour l'identifiant.

Du coup, j'ai supprimé la demande de compte vu qu'il a pu faire une demande d'accès avec son compte 2592898.
