### ISSUE TITLE
[GeoNature] : formulaire de création de compte (+ email)

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#76]
Mettre à jour le formulaire de création de compte : 
 - [x] Supprimer la case "j'accepte les conditions d'utilisation et les chartes des pôles"
 - [x] Remplacer le texte de l'encadré bleu par : 
    > Les données de Biodiv'AURA sont diffusées en accès libre avec leur précision géographique maximale, hors données sensibles, via le bouton "accès public". La création de compte est nécessaire uniquement pour demander un [accès à la localisation précise des données sensibles](https://www.biodiversite-auvergne-rhone-alpes.fr/wp-content/uploads/2024/05/acces_aux_donnees_sensibles_SINP_AURA-_VF2024.pdf).
    > Les données et informations qui vous sont fournies dans le cadre de Biodiv'AURA Expert ne sont pas exhaustives et peuvent donc s'avérer insuffisantes pour les besoins spécifiques de votre étude. Une réactualisation de ces données dans le cadre d'inventaires complémentaires est nécessaire.

**Comment by jpm-cbna** [comment]
Il y aussi ce texte envoyé dans les emails qu'il faudrait modifier :

        Nous vous rappelons que cette inscription vous donne accès à la consultation
        des données versées dans Biodiv'AURA Expert à l'échelle de la maille 5x5km.
        L'accès aux données précises nécessite de compléter un 
        «formulaire de demande d'accès aux données précises».
        L'accord sera formalisé par l'acceptation d'une convention 
        « droit d'accès aux données précises »
        et donnera lieu à l'attribution d'un accès direct à ces données.
        La convention engage le titulaire au bon usage des données et à l'alimentation
        de Bioviv'AURA Expert en retour.

**Comment by jpm-cbna** [comment]
Est ce que l'on ne rajouterait pas ceci à la fin de l'encadré bleu dans le formulaire d'inscription ?
 
    Vous êtes invité à partager en retour les données acquises dans le cadre de vos projet
    pour leur mise à disposition dans Biodiv’AURA Expert ([ plus d’informations relatives à la
    transmission de données ](https://www.biodiversite-auvergne-rhone-alpes.fr/transmettre-ses-donnees/)).

**Comment by okristo** [comment]
> Est ce que l'on ne rajouterait pas ceci à la fin de l'encadré bleu dans le formulaire d'inscription ?
> 
> ```
> Vous êtes invité à partager en retour les données acquises dans le cadre de vos projet
> pour leur mise à disposition dans Biodiv’AURA Expert ([ plus d’informations relatives à la
> transmission de données ](https://www.biodiversite-auvergne-rhone-alpes.fr/transmettre-ses-donnees/)).
> ```

Je le laisserais plutôt dans la convention.

**Comment by okristo** [comment]
> Il y aussi ce texte envoyé dans les emails qu'il faudrait modifier :
> 
> ```
>     Nous vous rappelons que cette inscription vous donne accès à la consultation
>     des données versées dans Biodiv'AURA Expert à l'échelle de la maille 5x5km.
>     L'accès aux données précises nécessite de compléter un 
>     «formulaire de demande d'accès aux données précises».
>     L'accord sera formalisé par l'acceptation d'une convention 
>     « droit d'accès aux données précises »
>     et donnera lieu à l'attribution d'un accès direct à ces données.
>     La convention engage le titulaire au bon usage des données et à l'alimentation
>     de Bioviv'AURA Expert en retour.
> ```

Remplacer par : 
Nous vous rappelons que les données de Biodiv'AURA sont diffusées en accès libre avec leur précision géographique maximale, hors données sensibles, via le bouton "accès public". La création de compte est nécessaire uniquement pour demander un [accès à la localisation précise des données sensibles](https://www.biodiversite-auvergne-rhone-alpes.fr/wp-content/uploads/2024/05/acces_aux_donnees_sensibles_SINP_AURA-_VF2024.pdf).
L'accès aux données sensibles précises nécessite de compléter un «formulaire de demande d'accès aux données sensibles précises».
L'accord sera formalisé par l'acceptation d'une convention « droit d'accès aux données sensibles précises » et donnera lieu à l'attribution d'un accès direct à ces données.
