### ISSUE TITLE
[GeoNature] Création de compte - mail de confirmation

### ISSUE THREAD

**Issue by okristo** [cbn-alpin/sinp-aura-tickets#9]
*** Ceci est un message généré automatiquement ***
Bonjour Ornella KRISTO,
Votre inscription à "Nom outil" a été acceptée.
Vous pouvez dès à présent vous connecter sur donnees.biodiversite-auvergne-rhone-alpes.fr
Pour rappel, votre identifiant de connexion est : ornella.kristo
Nous vous rappelons que cette inscription vous donne accès à la consultation des données versées dans Nom outil à l’échelle de la maille 5x5km.
L’accès aux données précises nécessite de compléter un « formulaire de demande d‘accès aux données précises ».
L'accord sera formalisé par l’acceptation d'une convention « droit d'accès aux données précises » et donnera lieu à l'attribution d'un accès direct à ces données.
La convention engage le titulaire au bon usage des données et à Nom outil en retour.
Bien cordialement,
l'administrateur.

**Comment by jpm-cbna** [comment]
Il me faudrait le lien vers la page du site web (CMS) qui contiendra un exemple de  convention « droit d'accès aux données précises ».

**Comment by jpm-cbna** [comment]
La dernière phrase c'est plutôt: « La convention engage le titulaire au bon usage des données et à **l'alimentation de** Nom outil en retour. » ?
Du coup, là aussi j'ai besoin du lien vers la page web permettant de contribuer...
